config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.  # Documentation Comment
  def full_title(page_title = '')                # Method def, optional arg
    base_title = "FurnHub"                     # Variable assignment
    if page_title.empty?                         # Booloean test
      base_title                                 # Implicit return
    else
      page_title + " | " + base_title            # String concatenation
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designed and Developed by <a href="https://linkedin.com/in/ridhanf/">Ridhan Fadhilah</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://www.instagram.com/furnhubid/">Instagram</a></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "About Us",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to "FurnHub", root_path, id: "logo" %>
      <!--<%= image_tag("logo.jpg", alt: "logo", :size => "100x50") %>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><a href="http://www.tokopedia.com/furnhub/">Store</a></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About Us", about_path %></li>
       </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p align="justify">
FurnHub merupakan usaha yang bergerak dalam 
bidang penyediaan furniture. Melalui FurnHub 
kami berkomitmen untuk menjadi rekan dari pelanggan 
kami serta seluruh elemen industri furniture. 
<br/><br/>
Visi besar kami adalah menjadi rekan yang akan anda 
hubungi apabila anda membutuhkan bantuan untuk 
kebutuhan furniture anda. Karena kami percaya, 
untuk mendapatkan suatu produk yang bernilai anda 
tidak perlu repot - repot melewati halangan apapun. 
Atas dasar hal tersebut lah FurnHub hadir untuk 
mempermudah anda menemukan produk yang sesuai.
<br/><br/>
Sebagai rekan anda, kami sangat percaya bahwa 
seharusnya bukan anda yang menyesuaikan diri 
terhadap barang yang anda miliki. Namun barang 
anda lah yang seharusnya sesuai dan bekerja untuk 
anda.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
Find us on:<br/>
<br/>
Email     : furnhubid@gmail.com  <br/>
Mobile    : +62-8231-3079-305  <br/>
Instagram : @furnhubid         <br/>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to <br/> <%= image_tag("logo.png", alt: "Meja", :size => "500x130")%></h1>
  <p>
    Buying furniture is incredibly easy <br/>
  </p>
</div>
<br/>
<center><%= image_tag("meja1.jpg", alt: "Meja", :size => "500x350")%></center>
<br/><br/>
<Center><%=image_tag("kursi1.jpg", alt: "Kursi", :size => "500x350")%></center>